But can I have it for dinner?
towerofnix/why-do-kids-love-the-taste-of-cinnamon-toast-crunch pull request #17
Opened 2024-06-24 23:24 UTC by blazgocompany

I finally found a repository that makes it easy to earn the Pull Shark badge. 😆

2024-06-24 23:28 UTC, blazgocompany commented
Thanks in advance if you do merge this. My profile page is looking bland.

2024-06-24 23:55 UTC, towerofnix requested changes
Beautiful! Thank you for sharing this newfound knowledge. Please add the missing space and update the code so that it's indented the same way as the other lines in the file (no need for blank lines inside the function either). Then it's perfect!

2024-06-24 23:55 UTC, towerofnix commented on index.js
> +return "Haven't heard of it, but you can have it for breakfast... and lunch..." +
There should be a space at the end of this line (inside the quotation marks).

2024-06-25 16:24 UTC, blazgocompany commented
Can you merge this now?

2024-06-25 20:38 UTC, towerofnix commented
Thanks for getting the space fixed up, but sorry, you'll still need to fix the indentation and remove the blank lines! Here is your current code:

```js

module.exports.butCanIHaveItForDinner = 
  function nobodyToldMeYouThatYouCould() {

return "Haven't heard of it, but you can have it for breakfast... and lunch... " + 
  "and as a snack... and pretty much whenever you want... " +
  "I guess that includes dinner too."

}
```

Here is what it should be:

```js
module.exports.butCanIHaveItForDinner = 
  function nobodyToldMeYouThatYouCould() {
    return "Haven't heard of it, but you can have it for breakfast... and lunch... " + 
    "and as a snack... and pretty much whenever you want... " +
    "I guess that includes dinner too."
  }
```

2024-06-25 22:14 UTC, blazgocompany commented
Oh ok.

2024-06-25 22:15 UTC, blazgocompany commented
Sorry about that

2024-06-26 12:17 UTC, towerofnix approved these changes
Thank you! We'll have this published on NPM as why-do-kids-love-the-taste-of-cinnamon-toast-crunch@3.3.0. 🎉

2024-06-26 12:17 UTC, merged

2024-06-26 14:08 UTC, blazgocompany commented
👍🏼